on: 
  push: 
    branches:
       - dev
jobs:
  pre-push_hook:
 
     runs-on: ubuntu-latest
     
     steps:
     - name: Checkout
       uses: actions/checkout@v3
       with:
         ref: dev
     - name: Install Talisman
       run: |
           wget https://github.com/thoughtworks/talisman/releases/latest/download/talisman_linux_amd64 -O talisman
           chmod +x talisman
           sudo mv talisman /usr/local/bin/
 
     - name: Run Talisman Checks
       run: talisman --scan 
       continue-on-error: true
 
     - name: Upload Report
       uses: actions/upload-artifact@v3
       with:
           name: talisman-scan-report
           path: talisman_report/talisman_reports/data
  Build_and_test:
     needs: pre-push_hook
     runs-on: ubuntu-latest
     
     steps:
     - name: Checkout
       uses: actions/checkout@v3
       with:
         ref: dev
     - name: Set up JDK 17
       uses: actions/setup-java@v3
       with:
         java-version: '17'
         distribution: 'temurin'
         #cache: maven
     
         
     - name: Build Maven
       run: mvn -B package --file pom.xml
 
     - name: Unit Test
       run: mvn --batch-mode -Dmaven.test.failure.ignore=false test
       
     - name: Build Test Maven
       run: mvn -B package --file pom.xml -DskipTests
     
       
     - name: Upload to Artifact  
       run: mkdir staging && cp target/*jar-with-dependencies.jar staging
     - uses: actions/upload-artifact@v3
       with:
             name: Package
             path: staging
     #- name: Nexus Repo Publish
      # uses: sonatype-nexus-community/nexus-repo-github-action@master
       #with:
        # serverUrl: https://annually-quality-seagull.ngrok-free.app
         #username: admin
         #password: ${{ secrets.password }}
         #format: maven2
         #repository: maven-GH
         #coordinates: groupId=com.example artifactId=app version=1.0.0
         #assets: extension=jar
         #filename: target/*jar-with-dependencies.jar
 
     
    
     - name: Generate SBOM
       run: mvn org.cyclonedx:cyclonedx-maven-plugin:makeAggregateBom 
         
      
     - name: Upload SBOM report to artifact
       uses: actions/upload-artifact@v3
       with:
           name: sbom
           path: target/bom.xml

     - name: Check out code
       uses: actions/checkout@v2
     
     - name: Set up Git
       run: |
             git config user.name "Your Name"
             git config user.email "your.email@example.com"
     
     - name: Create Version Tag
       run: |
             # Increment the version number, e.g., using Semantic Versioning
             # Replace this with your versioning logic
             chmod +x .github/workflows/config/increment.sh
             current_version=$(cat .github/workflows/config/increment.txt)
             new_version=$(.github/workflows/config/increment.sh "$current_version")
             echo "New version: $new_version"
             echo "::set-output name=new_version::$new_version"   
             git tag -a "v$new_version" -m "Version $new_version"
             git push origin --tags
  
 
  Docker_push:
     needs: Build_and_test
     runs-on: ubuntu-latest
     
     steps:
     - name: Checkout
       uses: actions/checkout@v3
       with:
         ref: dev
     - name: Login to DockerHub
       uses: docker/login-action@v2
       with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_TOKEN }}
     - name: Build and push Docker image
       uses: docker/build-push-action@v4
       with:
          context: .
          push: true
          tags: preethiagnes/app:${{ github.sha }}
     
       
  Deploy:
    needs: Docker_push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          repository: PreethiAgnes/Deployment   # Replace with the repository URL
          ref: main 
          token: ${{secrets.PAT_TOKEN }}

   
      - name: Modify Manifest
        run: |
            # Replace the image and tag in the manifest file
            sed -i 's|image: preethiagnes/app:*|image: preethiagnes/app:${{ github.sha}} T|' ./manifest/deployment.yaml

      - name: Commit and Push Change
        run: |
            git config --global user.name "PreethiAgnes"
            git config --global user.email "preethiagnest@gmail.com"
            git add ./manifest/deployment.yaml
            git commit -m "Update image tag with github.sha"
            git push origin main  
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
