name: Validate Branch Name Against JIRA

on:
  push:
    branches:
      - '*'

jobs:
  validate-branch-name:
    runs-on: ubuntu-latest

    steps:

      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Navigate to Repository Root
        run: cd $GITHUB_WORKSPACE
      
      - name: Configure Git
        run: |
          git config --global user.name "PreethiAgnes"
          git config --global user.email "preethiagnest@gmail.com"

      - name: Install jq
        run: sudo apt-get install jq

      - name: Debug
        run: set -x

      - name: Check if Jira Issue is In Progress
        id: check-jira-status
        run: |
          # Use the Jira REST API to fetch the status of the Jira issue
          # Replace with your Jira domain, issue key, and authentication
          curl -u ${{ secrets.JIRA_USERNAME }}:${{ secrets.JIRA_API_TOKEN }} -X GET "https://preethi-agnest.atlassian.net/rest/api/2/issue/DEV-1"

      - name: Get the current branch name
        run: |
            # Get the current branch name
            branch_name=$(git rev-parse --abbrev-ref HEAD)
            
            # Check if the branch name is empty or not found
            if [ -z "$branch_name" ]; then
              echo "Branch name not found. Exiting..."
              exit 1
            fi
            
            echo "Current branch is $branch_name"
        shell: bash
      - name: Check Branch Name and Jira Status
        run: |
            # Get the current branch name
            #branch_name=$(git branch --show-current 2>/dev/null)
            
            # Check if the branch name is empty or not found
            #if [ -z "$branch_name" ]; then
              #echo "Branch name not found. Exiting..."
              #exit 1
            #fi
            
            echo "Current branch is $branch_name"
            
            # Extract the issue key from the branch name
            issue_key=$(echo $branch_name | awk -F'-' '{print $1}')
            
            # Check if the issue key exists in the fetched Jira issue and if it's in progress
            if [[ ! "$(jq --arg key "$issue_key" '.key == $key and .fields.status.name == "In Progress"' <<< "")" == "true" ]]; then
              echo "Branch name '$branch_name' does not correspond to an issue in progress on the Jira board."
              exit 1
            }}
        env:
            GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
            JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
            JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}