name: Validate Branch Name Against JIRA

on:
  push:
    branches:
      - '*'

jobs:
  validate-branch-name:
    runs-on: ubuntu-latest

    steps:
      - name: Check if Jira Issue is In Progress
        id: check-jira-status
        run: |
          # Use the Jira REST API to fetch the status of the Jira issue
          # Replace with your Jira domain, issue key, and authentication
          curl -u ${{ secrets.JIRA_USERNAME }}:${{ secrets.JIRA_API_TOKEN }} -X GET "https://preethi-agnest.atlassian.net/rest/api/2/issue/DEV-1"
      - name: Get Current Branch Name
        run: |
            branch_name=$(git branch --show-current)
            echo "Current branch is $branch_name"
            issue_key=$(echo $branch_name | awk -F'-' '{print $1}')
  
            # Check if the issue key exists in the fetched Jira issue and if it's in progress
            if [[ ! "$(jq --arg key "$issue_key" '.key == $key and .fields.status.name == "In Progress"' <<< "${{ steps.check-jira-status.outputs.result }}")" == "true" ]]; then
              echo "Branch name '$branch_name' does not correspond to an issue in progress on the Jira board."
              exit 1
            fi
        env:
            GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
            JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
            JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}