jobs:
  validate_branches:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Get Jira Issues
      id: jira_issues
      run: |
          JIRA_DOMAIN="https://preethi-agnest.atlassian.net"
          JIRA_API_TOKEN="${{ secrets.JIRA_API_TOKEN }}"
          
          # Make a REST API request to Jira to retrieve a list of issues
          issues=$(curl -s -X GET "$JIRA_DOMAIN/jira/servicedesk/projects/DEV/queues/custom/1" -H "Authorization: Basic $JIRA_API_TOKEN")
          echo "$issues" > jira_issues.json
          
    - name: Iterate and Validate Branches
      run: |
          JIRA_DOMAIN="https://preethi-agnest.atlassian.net"
          JIRA_API_TOKEN="${{ secrets.JIRA_API_TOKEN }}"
          
          # Extract branch names from the repository
          branches=$(git for-each-ref --format='%(refname:short)' refs/heads/)
          
          # Loop through the branches and validate them
          for branch in $branches; do
            # Extract the Jira issue key from the branch name
            issue_key="${branch##*/}"  # Assumes branch name format: "feature/DEV-123-some-description"
            
            # Make a REST API request to Jira to retrieve issue details
            issue_details=$(curl -s -X GET "$JIRA_DOMAIN/rest/api/3/issue/$issue_key" -H "Authorization: Basic $JIRA_API_TOKEN")
            issue_status=$(echo "$issue_details" | jq -r '.fields.status.name')

            # Check if the issue is in progress
            if [ "$issue_status" != "In Progress" ]; then
              echo "Error: Jira issue $issue_key is not in progress."
              exit 1
            fi
          done
       env:
          JAVA_HOME: /opt/hostedtoolcache/Java_Adopt_jdk/11.0.20-101/x64
          JIRA_DOMAIN: https://preethi-agnest.atlassian.net
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
