name: On Push hook

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - '!prd'
      - '!qa'

jobs:
  validate_branches:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Get Jira Issues
      id: jira_issues
      run: |
          JIRA_DOMAIN="https://preethi-agnest.atlassian.net"
          JIRA_API_TOKEN="${{ secrets.JIRA_API_TOKEN }}"
          
          # Make a REST API request to Jira to retrieve a list of issues
          issues=$(curl -s -X GET "$JIRA_DOMAIN/jira/servicedesk/projects/DEV/queues/custom/1" -H "Authorization: Basic $JIRA_API_TOKEN")
          echo "$issues" > jira_issues.json

    - name: Debug Jira Issue Status
      run: |
            echo "Issue Key: $issue_key"
            echo "Issue Status: $issue_status"
        
          
    - name: Check Jira Ticket Status
      env:
              JIRA_URL: ${{ secrets.JIRA_URL }}
              JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
              JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
              JIRA_PROJECT_KEY: DEV
              JIRA_ISSUE_KEY: DEV-1
      run: |
              # Fetch the Jira issue statu
              issue_status=$(curl -s -u $JIRA_USERNAME:$JIRA_API_TOKEN -X GET $JIRA_URL/rest/api/2/issue/$JIRA_ISSUE_KEY | jq -r '.fields.status.name')
              
              echo "Issue Status: $issue_status"
              
              # Check if the issue is in progress
              if [ "$issue_status" == "In Progress" ]; then
                echo "The Jira issue $JIRA_ISSUE_KEY is in progress."
                # Perform actions specific to when the issue is in progress
              else
                echo "The Jira issue $JIRA_ISSUE_KEY is not in progress."
                # Perform actions specific to when the issue is not in progress
              fi
          
